### ISSUE TITLE
Missing essencial files

### ISSUE THREAD

**Issue by mushroomwjy** [wanweilin/WinCLIP#2]
What does the path "dataset/dtd" mean? Could not read the "anomaly_source_paths" without this folder.
![屏幕截图 2024-03-14 202735](https://github.com/wanweilin/WinCLIP/assets/109121110/c1abe0fe-55ee-4647-bc91-bd3845a61eed)

**Comment by wanweilin** [comment]
The 'anomaly_source_path' refers to the Textures dataset, which is utilized as the source of anomalous images in our experiments. The homepage URL for the Textures dataset is https://www.robots.ox.ac.uk/~vgg/data/dtd/. This dataset contains a wide variety of texture images, which are used as anomalous samples in anomaly detection tasks. I hope this clears up the purpose of this section of the code for you.

I would like to add that, in the current implementation, this anomaly source does not play an active role in the functionality of the system. Instead, it was used to help me understand how the CLIP model perceives features in the space of anomalies.
